/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.CustomerController;
import Model.CustomerModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class ChangeCustomerView extends javax.swing.JDialog {

    /**
     * Creates new form ChangeCustomerView
     */
    private CustomerController cusDAO = new CustomerController();
    
    public ChangeCustomerView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private boolean setSex(String s) {
        return s.equals("Male") ? true : false;
    }
    
    public void setItems(String cmnd, String first, String last, String sex, String phone, String date, String address, String job) throws ParseException {
        this.cmndTxt.setText(cmnd);
        this.firstTxt.setText(first);
        this.lastTxt.setText(last);
        if(setSex(sex)) {
            male.setSelected(true);
        } else {
            female.setSelected(true);
        }

        this.phoneTxt.setText(phone);
        
        // Convert String to Date.
        Date d = new SimpleDateFormat("yyyy-MM-dd").parse(date);
        this.dateBirth.setDate(d);
        
        this.addressTxt.setText(address);
        this.jobTxt.setText(job);
        
        this.cmndTxt.setEditable(false);
    }
    
    
    private  String convertUpper(String s) {
        String[] words = s.toLowerCase().split("\\s+");
        StringBuilder builder = new StringBuilder();
        for (var item : words) {
            char[] characters = item.toCharArray();
            characters[0] = Character.toUpperCase(characters[0]);
            builder.append(new String(characters));
            builder.append(" ");
        }
       
        return builder.toString().trim();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGR = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmndTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        firstTxt = new javax.swing.JTextField();
        errFirst = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lastTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        errPhone = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dateBirth = new com.toedter.calendar.JDateChooser();
        errDate = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        male = new javax.swing.JCheckBox();
        female = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        errAddress = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jobTxt = new javax.swing.JTextField();
        errJob = new javax.swing.JLabel();
        changeBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE CUSTOMER INFORMATION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("CMND/CCCD");

        cmndTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("First Name");

        firstTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errFirst.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errFirst.setForeground(new java.awt.Color(255, 0, 0));
        errFirst.setText(" ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Last Name");

        lastTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Phone Number");

        phoneTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errPhone.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errPhone.setForeground(new java.awt.Color(255, 0, 0));
        errPhone.setText(" ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Date of Birth");

        dateBirth.setBackground(new java.awt.Color(255, 255, 255));
        dateBirth.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errDate.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errDate.setForeground(new java.awt.Color(255, 0, 0));
        errDate.setText(" ");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Sex");

        male.setBackground(new java.awt.Color(255, 255, 255));
        btGR.add(male);
        male.setText("Male");

        female.setBackground(new java.awt.Color(255, 255, 255));
        btGR.add(female);
        female.setText("Female");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Address");

        addressTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errAddress.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errAddress.setForeground(new java.awt.Color(255, 0, 0));
        errAddress.setText(" ");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Job");

        jobTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errJob.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errJob.setForeground(new java.awt.Color(255, 0, 0));
        errJob.setText(" ");

        changeBT.setBackground(new java.awt.Color(255, 255, 255));
        changeBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-change-contract-32.png"))); // NOI18N
        changeBT.setText("CHANGE");
        changeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBTActionPerformed(evt);
            }
        });

        cancelBT.setBackground(new java.awt.Color(255, 255, 255));
        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-circled-x-32.png"))); // NOI18N
        cancelBT.setText("CANCEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(jLabel2)
                            .addComponent(cmndTxt)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(firstTxt)
                                    .addComponent(jLabel17)
                                    .addComponent(dateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(male)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                            .addComponent(female))
                                        .addComponent(lastTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(phoneTxt)
                            .addComponent(errPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errDate, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(addressTxt)
                            .addComponent(errAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jobTxt)
                            .addComponent(errJob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(changeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errFirst)
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errPhone)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male)
                        .addComponent(female)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errDate)
                .addGap(26, 26, 26)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errAddress)
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errJob)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBTActionPerformed
        // TODO add your handling code here:
        
        String cmnd =  cmndTxt.getText();
        String first =  firstTxt.getText();
        String last =  lastTxt.getText();
        boolean sex = male.isSelected();
        
        Date dob = dateBirth.getDate();
        
        String phone = phoneTxt.getText();
        String address = addressTxt.getText();
        String job = jobTxt.getText();
        
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
        Date d = new Date();
        sdm.format(d);
        
        
        if(first.equals("")) {
            errFirst.setText("Please enter your first name");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if(!first.matches("[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ ]+$")) {
            errFirst.setText("First name can't contain numeric or special characters");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if (last.equals("")) {
            errFirst.setText("Please enter your last name");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if(!last.matches("[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ ]+$")) {
            errFirst.setText("Last name can't contain numeric or special characters");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if (phone.equals("")) {
            errFirst.setText(" ");
            errPhone.setText("Please enter your phone number");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if (!phone.matches("^\\d{10}$")) {
            errFirst.setText(" ");
            errPhone.setText("Invalid Phone number");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if (dob == null) {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText("Please enter your date of birth");
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if (dob.compareTo(d) > 0) {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText("Date of Birth must not exceed " + sdm.format(d));
            errAddress.setText(" ");
            errJob.setText(" ");
        } else if (address.equals("")) {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText("Please enter your address");
            errJob.setText(" ");
        } else if(!address.matches("^[a-zA-Z0-9ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ, ]+$")) {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText(" ");
            errJob.setText(" ");
            errAddress.setText("Address contain alphanumeric characters and character(,)");
        } else if (job.equals("")) {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText("Please enter your job");
        } else if(!job.matches("^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ ]+$")) {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText(" ");
            errJob.setText("Cannot contain numeric or special characters");
            errAddress.setText(" ");
        } else {
            errFirst.setText(" ");
            errPhone.setText(" ");
            errDate.setText(" ");
            errAddress.setText(" ");
            errJob.setText(" ");
            
            
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            String birth = s.format(dob);
            
            CustomerModel cus = new CustomerModel (cmnd, convertUpper(first), convertUpper(last), sex, birth, phone, address, job, true);
            
            if (cusDAO.updateCustomer(cus)) {
                JOptionPane.showMessageDialog(rootPane, "Successfully!!!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed!!!");
                this.dispose();
            }
        }
        
        
    }//GEN-LAST:event_changeBTActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChangeCustomerView dialog = new ChangeCustomerView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.ButtonGroup btGR;
    private javax.swing.JButton cancelBT;
    private javax.swing.JButton changeBT;
    private javax.swing.JTextField cmndTxt;
    private com.toedter.calendar.JDateChooser dateBirth;
    private javax.swing.JLabel errAddress;
    private javax.swing.JLabel errDate;
    private javax.swing.JLabel errFirst;
    private javax.swing.JLabel errJob;
    private javax.swing.JLabel errPhone;
    private javax.swing.JCheckBox female;
    private javax.swing.JTextField firstTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jobTxt;
    private javax.swing.JTextField lastTxt;
    private javax.swing.JCheckBox male;
    private javax.swing.JTextField phoneTxt;
    // End of variables declaration//GEN-END:variables
}
