/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.RoomController;
import Controller.StatusRoomController;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author nguye
 */
public class ChangeRoomView extends javax.swing.JDialog {

    /**
     * Creates new form ChangeRoomView
     */
    
    public String max;
    public String prc;
    public String s;
    private RoomController roomDAO = new RoomController();
    private StatusRoomController statusDAO = new StatusRoomController();
    public ChangeRoomView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setModel(String idR, String idM, int max, double price, String status) {
        this.idRText.setText(idR);
        this.idMTxt.setText(idM);
        this.maxTxt.setText(String.valueOf(max));
        this.priceTxt.setText(String.valueOf(price));
        
        
        if (!status.equals("Chưa có người thuê")) {
            this.priceTxt.setEditable(false);
        } else {
             this.priceTxt.setEditable(true);
        }
                
        
        this.statusCB.setSelectedItem(status);
        this.idRText.setEditable(false);
        this.idMTxt.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idRText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idMTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        errPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        maxTxt = new javax.swing.JTextField();
        errMax = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        errSts = new javax.swing.JLabel();
        updateBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        statusCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE ROOM INFORMATION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID Room");

        idRText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ID Motel");

        idMTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Price Room");

        priceTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errPrice.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errPrice.setForeground(new java.awt.Color(255, 0, 0));
        errPrice.setText(" ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Max quantity");

        maxTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errMax.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errMax.setForeground(new java.awt.Color(255, 0, 0));
        errMax.setText(" ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Status Room");

        errSts.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errSts.setForeground(new java.awt.Color(255, 0, 0));
        errSts.setText(" ");

        updateBT.setBackground(new java.awt.Color(255, 255, 255));
        updateBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-change-contract-32.png"))); // NOI18N
        updateBT.setText("UPDATE");
        updateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTActionPerformed(evt);
            }
        });

        cancelBT.setBackground(new java.awt.Color(255, 255, 255));
        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-circled-x-32.png"))); // NOI18N
        cancelBT.setText("CANCEL");

        statusCB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa có người thuê", "Đã có người thuê", "Đã đủ số lượng", "Đang bảo trì" }));
        statusCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(idRText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addComponent(priceTxt)
                        .addComponent(errPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxTxt)
                        .addComponent(errMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errSts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusCB, 0, 379, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idRText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errPrice)
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errMax)
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errSts)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        
        String sts = statusCB.getItemAt(statusCB.getSelectedIndex());
        int crr =  roomDAO.getCurrent(idRText.getText());
        
        if(maxTxt.getText().equals("")) {
            errMax.setText("Please enter Max quantity");
            errPrice.setText(" ");
            errSts.setText(" ");
        } else if (!maxTxt.getText().matches("[0-9]+")) {
            errMax.setText("Max quantity contain numeric characters and not less than 1");
            errPrice.setText(" ");
            errSts.setText(" ");
        } else if (Integer.valueOf(maxTxt.getText()) < 1) {
            errSts.setText(" ");
            errMax.setText("Max quantity not less than 0");
            errPrice.setText(" ");
        } else if (crr > Integer.valueOf(maxTxt.getText())) {
            errMax.setText("Max quantity not less than Current Quantity: " + crr);
            errPrice.setText(" ");
            errSts.setText(" ");
        }  else if (priceTxt.getText().equals("")) {
            errSts.setText(" ");
            errMax.setText(" ");
            errPrice.setText("Please enter Price room");
        } else if (!priceTxt.getText().matches("[0-9.]+")) {
            errMax.setText(" ");
            errPrice.setText("Price quantity contain numeric characters");
            errSts.setText(" ");
        }  else if (Double.valueOf(priceTxt.getText()) < 100000) {
            errSts.setText(" ");
            errMax.setText(" ");
            errPrice.setText("Price room not less than 100.000 VND");
        } else if ((crr > 0 && crr < Integer.valueOf(maxTxt.getText())) && (sts.equals("Đã đủ số lượng") || sts.equals("Chưa có người thuê") || sts.equals("Đang bảo trì"))) {
            errMax.setText(" ");
            errPrice.setText(" ");
            errSts.setText("The room status cannot be changed to because the room is currently rented");
        } else if (crr == Integer.valueOf(maxTxt.getText()) && sts.equals("Đã có người thuê")) {
            errMax.setText(" ");
            errPrice.setText(" ");
            errSts.setText("The room status cannot be changed because the room is full");
        } else if (crr == Integer.valueOf(maxTxt.getText()) && (sts.equals("Chưa có người thuê") || sts.equals("Đang bảo trì"))) {
            errMax.setText(" ");
            errPrice.setText(" ");
            errSts.setText("The room status cannot be changed to because the room is currently rented");
        } else {
            errMax.setText(" ");
            errPrice.setText(" ");
            errSts.setText(" ");
            
            String idS = statusDAO.getID(sts);
            
            if(roomDAO.updateRoom(idRText.getText(), Integer.valueOf(maxTxt.getText()), Double.valueOf(priceTxt.getText()), idS)) {
                JOptionPane.showMessageDialog(rootPane, "Successfully!!!");
                max = maxTxt.getText();
                prc = priceTxt.getText();
                s = sts;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed!!!");
                this.dispose();
            }
        }
    }//GEN-LAST:event_updateBTActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChangeRoomView dialog = new ChangeRoomView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBT;
    private javax.swing.JLabel errMax;
    private javax.swing.JLabel errPrice;
    private javax.swing.JLabel errSts;
    private javax.swing.JTextField idMTxt;
    private javax.swing.JTextField idRText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JButton updateBT;
    // End of variables declaration//GEN-END:variables
}
