/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.BillController;
import Controller.BillDetailController;
import Controller.RoomController;
import Controller.ServiceController;
import Model.BillDetailModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class ChangeBillView extends javax.swing.JDialog {

    /**
     * Creates new form ChangeBillView
     */
    
    private BillDetailController billDetailDAO = new BillDetailController();
    private ServiceController serDAO = new ServiceController();
    private BillController billDAO = new BillController();
    private RoomController roomDAO = new RoomController();
    private String idR;
    public ChangeBillView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public void setItems(String idB, float oldElec, float oldWater, float newElec, float newWater, String idR) {
        this.idBText.setText(idB);
        this.oldElecTxt.setText(String.valueOf(oldElec));
        this.oldWaterTxt.setText(String.valueOf(oldWater));
        this.newElecTxt.setText(String.valueOf(newElec));
        this.newWaterTxt.setText(String.valueOf(newWater));
        this.idR = idR;
        this.idBText.setEditable(false);
        this.oldElecTxt.setEditable(false);
        this.oldWaterTxt.setEditable(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idBText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        oldElecTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newElecTxt = new javax.swing.JTextField();
        errElec = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oldWaterTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        newWaterTxt = new javax.swing.JTextField();
        errWater = new javax.swing.JLabel();
        changeBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE BILL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID Bill");

        idBText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Old electric index");

        oldElecTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("New electric index");

        newElecTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errElec.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errElec.setForeground(new java.awt.Color(255, 0, 0));
        errElec.setText(" ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Old water index");

        oldWaterTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("New water index");

        newWaterTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errWater.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errWater.setForeground(new java.awt.Color(255, 0, 0));
        errWater.setText(" ");

        changeBT.setBackground(new java.awt.Color(255, 255, 255));
        changeBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-invoice-32-change.png"))); // NOI18N
        changeBT.setText("CHANGE");
        changeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBTActionPerformed(evt);
            }
        });

        cancelBT.setBackground(new java.awt.Color(255, 255, 255));
        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-circled-x-32.png"))); // NOI18N
        cancelBT.setText("CANCEL");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(changeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idBText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldElecTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newElecTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldWaterTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newWaterTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errElec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errWater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldElecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newElecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errElec)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldWaterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newWaterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errWater)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBTActionPerformed
        // TODO add your handling code here:
        
        if(newElecTxt.getText().equals("")) {
            errElec.setText("Please enter New electric index");
            errWater.setText(" ");
        } else if(!newElecTxt.getText().matches("[0-9.]+")) {
            errElec.setText("New electric contain numeric characters");
            errWater.setText(" ");
        } else if (Float.valueOf(newElecTxt.getText()) < 0) {
            errElec.setText("New electric index not less than 0");
            errWater.setText(" ");
        } else if (Float.valueOf(newElecTxt.getText()) < Float.valueOf(oldElecTxt.getText())) {
            errElec.setText("New electric index not less than old index: " + Float.valueOf(oldElecTxt.getText()));
            errWater.setText(" ");
        } else if(newWaterTxt.getText().equals("")) {
            errWater.setText("Please enter New electric index");
            errElec.setText(" ");
        } else if(!newWaterTxt.getText().matches("[0-9.]+")) {
            errElec.setText(" ");
            errWater.setText("New water contain numeric characters");
        } else if (Float.valueOf(newWaterTxt.getText()) < 0) {
            errWater.setText("New electric index not less than 0");
            errElec.setText(" ");
        } else if (Float.valueOf(newWaterTxt.getText()) < Float.valueOf(oldWaterTxt.getText())) {
            errWater.setText("New electric index not less than old index: " + Float.valueOf(oldWaterTxt.getText()));
            errElec.setText(" ");
        } else {
            errElec.setText(" ");
            errWater.setText(" ");
            
            double priceElec  = serDAO.getPrice("D");
            double priceWater = serDAO.getPrice("N");
            
            double totalElec = (Float.valueOf(newElecTxt.getText()) - Float.valueOf(oldElecTxt.getText())) * priceElec;
            double totalWater = (Float.valueOf(newWaterTxt.getText()) - Float.valueOf(oldWaterTxt.getText())) * priceWater;
            
            BillDetailModel billElec = new BillDetailModel(idBText.getText(), "D", priceElec, Float.valueOf(oldElecTxt.getText()), Float.valueOf(newElecTxt.getText()), totalElec, null);
            BillDetailModel billWater = new BillDetailModel(idBText.getText(), "N", priceElec, Float.valueOf(oldWaterTxt.getText()), Float.valueOf(newWaterTxt.getText()), totalWater, null);

            if (billDetailDAO.updateBillDetail(billElec) && billDetailDAO.updateBillDetail(billWater)) {
                
                
                double totalBill = totalElec + totalWater + serDAO.getPrice("I") + serDAO.getPrice("R") + roomDAO.getPriceRoom(idR);
                billDAO.updateTotalMoney(idBText.getText(), totalBill);
                JOptionPane.showMessageDialog(rootPane, "Successfully!!!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed!!!");
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_changeBTActionPerformed

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "You want to cancel?", "Message", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_cancelBTActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChangeBillView dialog = new ChangeBillView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBT;
    private javax.swing.JButton changeBT;
    private javax.swing.JLabel errElec;
    private javax.swing.JLabel errWater;
    private javax.swing.JTextField idBText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newElecTxt;
    private javax.swing.JTextField newWaterTxt;
    private javax.swing.JTextField oldElecTxt;
    private javax.swing.JTextField oldWaterTxt;
    // End of variables declaration//GEN-END:variables
}
