/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.ContractController;
import Controller.ContractDetailController;
import Controller.CustomerController;
import Controller.RoomController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class CheckOutView extends javax.swing.JDialog {

    /**
     * Creates new form CheckOutView
     */
    private String idR, idC, cmnd;
    private ContractController contractDAO = new ContractController();
    private ContractDetailController detailDAO = new ContractDetailController();

    public boolean flag = false;

    public CheckOutView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setItems(String idR, String idC, String cmnd) {
        this.cmnd = cmnd;
        this.idC = idC;
        this.idR = idR;
        this.dateCheckOut.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateCheckOut = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        okBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        errDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        dateCheckOut.setDateFormatString("MMMM dd, y");
        dateCheckOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Check out date");

        okBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        okBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick-inside-circle.png"))); // NOI18N
        okBT.setText("OK");
        okBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTActionPerformed(evt);
            }
        });

        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-circled-x-32.png"))); // NOI18N
        cancelBT.setText("CANCEL");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });

        errDate.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errDate.setForeground(new java.awt.Color(255, 0, 0));
        errDate.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(okBT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(cancelBT))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(errDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errDate)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "You want to cancel?", "Message", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {
            flag = false;
            this.dispose();
        }
    }//GEN-LAST:event_cancelBTActionPerformed

    private void okBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTActionPerformed
        // TODO add your handling code here:

        String staDay = detailDAO.getStartDate(cmnd, idC);

        SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
        Date dd = null;

        try {
            dd = new SimpleDateFormat("yyyy-MM-dd").parse(staDay);
        } catch (ParseException ex) {
            Logger.getLogger(CheckOutView.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (dateCheckOut.getDate() == null) {
            errDate.setText("Check out date cannot be left empty");
        } else if (dateCheckOut.getDate().compareTo(dd) < 0) {
            errDate.setText("Check out date not less than Start day: " + sdm.format(dd));
        } else {
            errDate.setText(" ");
            if (JOptionPane.showConfirmDialog(rootPane, "You want to check-out ?", "Message", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {
                Date d = dateCheckOut.getDate();
                SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
                String date = s.format(d);
                
                if (detailDAO.updateEndDayCurrent(cmnd, idC, date)) {
                    flag = true;
                    
                    // Cập nhật lại khách đang không thuê phòng nào
                    new CustomerController().updateRentalStatus(cmnd, false);
                    
                    // Lấy ra tổng hợp đồng đã trả của phòng X
                    int expiredSts = detailDAO.getCountStatusExprixeContractDetail(idC);
                    
                    // Lấy ra tổng hợp đồng của phòng X.
                    int totalSts = detailDAO.getTotalStatusContractDetail(idC);
                    
                    
                    
                    int crr = new RoomController().getCurrent(idR);
                    
                    // Nếu phòng X trả hết khách thì cập nhật hợp đồng phòng X là ngày ra muộn nhất của khách.
                    if (expiredSts == totalSts) {
                        String maxDate = detailDAO.getMaxEndDate(idC);
                        if (new ContractController().updateCheckOutDate(idC, maxDate)) {
                            if (new RoomController().updateStatusRooom(idR, 0, "TT1")) {
                                JOptionPane.showMessageDialog(rootPane, "Successfully");
                                this.dispose();
                            }
                        }
                    } else {
                        if (new RoomController().updateStatusRooom(idR, crr - 1, "TT2")) {
                            JOptionPane.showMessageDialog(rootPane, "Successfully");
                            this.dispose();
                        }
                    }
                    

                }
            }
        }
    }//GEN-LAST:event_okBTActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CheckOutView dialog = new CheckOutView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBT;
    private com.toedter.calendar.JDateChooser dateCheckOut;
    private javax.swing.JLabel errDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okBT;
    // End of variables declaration//GEN-END:variables
}
