/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.CustomerController;
import Controller.RoomController;
import Model.CustomerModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class CheckNewOrOldCustomerView extends javax.swing.JDialog {

    /**
     * Creates new form CheckNewOrOldCustomerView
     */
    private CustomerController cusDAO = new CustomerController();
    public double priceRoom = 0;
    public String idR = "";

    public int max = 0;
    public int current = 0;
    public CheckNewOrOldCustomerView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmndTxt = new javax.swing.JTextField();
        errCMND = new javax.swing.JLabel();
        nextBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        newCusCB = new javax.swing.JCheckBox();
        oldCusCB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CMND");

        cmndTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        errCMND.setForeground(new java.awt.Color(255, 0, 0));
        errCMND.setText(" ");

        nextBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login1.png"))); // NOI18N
        nextBT.setText("NEXT");
        nextBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTActionPerformed(evt);
            }
        });

        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-back-arrow-32.png"))); // NOI18N
        cancelBT.setText("CANCEL");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });

        newCusCB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(newCusCB);
        newCusCB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newCusCB.setText("New customer");

        oldCusCB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(oldCusCB);
        oldCusCB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        oldCusCB.setSelected(true);
        oldCusCB.setText("Old customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oldCusCB)
                        .addGap(18, 18, 18)
                        .addComponent(newCusCB))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(nextBT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                            .addComponent(cancelBT))
                        .addComponent(cmndTxt)
                        .addComponent(jLabel1)
                        .addComponent(errCMND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errCMND)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCusCB)
                    .addComponent(oldCusCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTActionPerformed
        // TODO add your handling code here:
        
        if (cmndTxt.getText().equals("")) {
            errCMND.setText("Please enter CMND");
        } else if (!cmndTxt.getText().matches("^\\d{12}$") && !cmndTxt.getText().matches("^\\d{9}$")) {
            errCMND.setText("Invalid CMND/CCCD");
        } else if (!cusDAO.checkCustomer(cmndTxt.getText()) && oldCusCB.isSelected() && !cusDAO.getRentalStatus(cmndTxt.getText()))   {
            CustomerModel cus = cusDAO.getCustomerWithCMND(cmndTxt.getText());
            AddCustomerView addCus = new AddCustomerView( (java.awt.Frame) this.getParent(), true);
            Date dob = null;

            try {
                dob = new SimpleDateFormat("yyyy-MM-dd").parse(cus.getDateOfBirth());
            } catch (ParseException ex) {
                Logger.getLogger(CheckOutView.class.getName()).log(Level.SEVERE, null, ex);
            }
            addCus.setItems(cus.getCMND(), cus.getFirstName(), cus.getLastName(), cus.getPhoneNumber(), dob, cus.isSex(), cus.getAddress(), cus.getJob());
            addCus.setIDAndMoney(idR, priceRoom);
            addCus.checkOldOrNew = false;
            addCus.setVisible(true);
            
            if (addCus.checkAdd) {
                cmndTxt.setText("");
                errCMND.setText(" ");
                if (new RoomController().getCurrent(idR) == new RoomController().getMax(idR) ) {
                    JOptionPane.showMessageDialog(rootPane, "Room is full");
                    this.dispose();
                }
            }
        } else if (!cusDAO.checkCustomer(cmndTxt.getText()) && oldCusCB.isSelected() && cusDAO.getRentalStatus(cmndTxt.getText()))   {
            errCMND.setText("This CMND/CCCD is renting a room");
        } else if (cusDAO.checkCustomer(cmndTxt.getText()) && oldCusCB.isSelected())   {
            errCMND.setText("CMND/CCCD not exists");
        } else if (!cusDAO.checkCustomer(cmndTxt.getText()) && !oldCusCB.isSelected())   {
            errCMND.setText("CMND/CCCD already exists");
        } else {
            errCMND.setText(" ");
            AddCustomerView addCus = new AddCustomerView( (java.awt.Frame) this.getParent(), true);
            addCus.setIDAndMoney(idR, priceRoom);
            addCus.setCMND(cmndTxt.getText());
            addCus.checkOldOrNew = true;
            addCus.setVisible(true);
            
            if (addCus.checkAdd) {
                cmndTxt.setText("");
                errCMND.setText(" ");
                if (new RoomController().getCurrent(idR) == new RoomController().getMax(idR) ) {
                    JOptionPane.showMessageDialog(rootPane, "Room is full");
                    this.dispose();
                }
            }
        }
        
    }//GEN-LAST:event_nextBTActionPerformed

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBTActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CheckNewOrOldCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CheckNewOrOldCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CheckNewOrOldCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CheckNewOrOldCustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CheckNewOrOldCustomerView dialog = new CheckNewOrOldCustomerView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBT;
    private javax.swing.JTextField cmndTxt;
    private javax.swing.JLabel errCMND;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox newCusCB;
    private javax.swing.JButton nextBT;
    private javax.swing.JCheckBox oldCusCB;
    // End of variables declaration//GEN-END:variables
}
