/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.BillController;
import Controller.BillDetailController;
import Controller.ContractController;
import Controller.RoomController;
import Controller.ServiceController;
import Model.BillDetailModel;
import Model.BillModel;
import Model.ServiceModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class CreateBillView extends javax.swing.JDialog {

    /**
     * Creates new form CreateBillView
     */
    private ArrayList<ServiceModel> listService = new ArrayList<>();
    private ServiceController serDAO = new ServiceController();
    private ContractController contractDAO = new ContractController();
    private BillController billDAO = new BillController();
    private BillDetailController billDetailDAO = new BillDetailController();
    
    private RoomController roomDAO = new RoomController();
    public CreateBillView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        listService = serDAO.getListService();
        
        
        
    }

    public void setIDR(String id) {
        this.idR.setText(id);
        this.idR.setEditable(false);
        
        
        
        // Lấy ID Contract cần lập bill
        String idC = contractDAO.getIDContract(idR.getText());
        
        
        
        // Lấy stt bill để tìm được bill lập gần nhất.
        int sttBill = billDAO.getMaxSTTBill(idC);
        String idB = billDAO.getIDBill(sttBill);
        
        float oldIndexElectric = billDetailDAO.getNewIndex(idB, "D");
        float oldIndexWater = billDetailDAO.getNewIndex(idB, "N");
        
        
        
        this.oldElecText.setText(String.valueOf(oldIndexElectric));
        this.oldWaterTxt.setText(String.valueOf(oldIndexWater));
        
        this.oldElecText.setEditable(false);
        this.oldWaterTxt.setEditable(false);
        
        for(ServiceModel model : listService) {
            if(model.getIdService().equals("D")) {
                this.priceElecTxt.setText(String.valueOf(serDAO.getPrice(model.getIdService())));
            } else if(model.getIdService().equals("I")) {
                this.priceInternet.setText(String.valueOf(serDAO.getPrice(model.getIdService())));
            } else if (model.getIdService().equals("N")) {
                this.priceWater.setText(String.valueOf(serDAO.getPrice(model.getIdService())));
            } else if (model.getIdService().equals("R")) {
                this.priceTrash.setText(String.valueOf(serDAO.getPrice(model.getIdService())));
            }
        }
        
        this.internetTxt.setText("1");
        this.trashTxt.setText("1");
        
        // Set tự động lập hóa đơn theo từng tháng
        int monCollection = billDAO.getMonthCollectionDate(idC, sttBill);
        int yearCollection = billDAO.getYearCollectionDate(idC, sttBill);
        
        if(monCollection == 0 && yearCollection == 0) {
            monCollection = contractDAO.getMonthContractBill(idC) - 1;
            yearCollection = contractDAO.getYearContractBill(idC);
            this.yearTxt.setYear(yearCollection);
            this.monthTxt.setMonth(monCollection);
        } else {
            this.yearTxt.setYear(yearCollection);
            this.monthTxt.setMonth(monCollection);

            if (monCollection == 12) {
                this.monthTxt.setMonth(0);
                this.yearTxt.setYear(yearCollection + 1);
            }
        }
        
        
        
        
        this.monthTxt.setEnabled(false);
        this.yearTxt.setEnabled(false);
        this.internetTxt.setEditable(false);
        this.trashTxt.setEditable(false);
        this.priceElecTxt.setEditable(false);
        this.priceInternet.setEditable(false);
        this.priceWater.setEditable(false);
        this.priceTrash.setEditable(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        elecTxt = new javax.swing.JTextField();
        errElec = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        priceElecTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        waterTxt = new javax.swing.JTextField();
        errWater = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        priceWater = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        internetTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        priceInternet = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        trashTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        priceTrash = new javax.swing.JTextField();
        addCusBT = new javax.swing.JButton();
        clcBT = new javax.swing.JButton();
        yearTxt = new com.toedter.calendar.JYearChooser();
        monthTxt = new com.toedter.calendar.JMonthChooser();
        jLabel3 = new javax.swing.JLabel();
        oldElecText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        oldWaterTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE BILL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID Room");

        idR.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Month");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("New electric index (kWh)");

        elecTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errElec.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errElec.setForeground(new java.awt.Color(255, 0, 0));
        errElec.setText(" ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Price");

        priceElecTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("New  water index (m3)");

        waterTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        errWater.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errWater.setForeground(new java.awt.Color(255, 0, 0));
        errWater.setText(" ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Price");

        priceWater.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Internet (room/month)");

        internetTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Price");

        priceInternet.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Trash (room/month)");

        trashTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Price");

        priceTrash.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        addCusBT.setBackground(new java.awt.Color(255, 255, 255));
        addCusBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCusBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-32.png"))); // NOI18N
        addCusBT.setText("ADD");
        addCusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusBTActionPerformed(evt);
            }
        });

        clcBT.setBackground(new java.awt.Color(255, 255, 255));
        clcBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clcBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-circled-x-32.png"))); // NOI18N
        clcBT.setText("CANCEL");
        clcBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clcBTActionPerformed(evt);
            }
        });

        monthTxt.setDayChooser(null);
        monthTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Old electric index (kWh)");

        oldElecText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Old water index (kWh)");

        oldWaterTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(internetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(idR)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(elecTxt)
                                            .addGap(28, 28, 28)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(priceElecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel16)
                                        .addComponent(priceInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(150, 150, 150))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(trashTxt)
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(priceTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(errWater, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(waterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                    .addComponent(priceWater, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(errElec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oldElecText))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oldWaterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(addCusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(clcBT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldElecText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(elecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceElecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errElec)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oldWaterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(waterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceWater, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(errWater)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(internetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trashTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clcBT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusBTActionPerformed
        // TODO add your handling code here:
       
        // Lấy ID Contract cần lập bill
        String idC = contractDAO.getIDContract(idR.getText());
        
        // Lấy stt bill để tìm được bill lập gần nhất.
        int sttBill = billDAO.getMaxSTTBill(idC);
        String idB = billDAO.getIDBill(sttBill);
        
        // Lấy ra chỉ số mới của tháng N thành chỉ số cũ của tháng N + 1.
        float oldIndexElectric = billDetailDAO.getNewIndex(idB, "D");
        float oldIndexWater = billDetailDAO.getNewIndex(idB, "N");
        
       
        
        // Kiểm tra điều kiện
        if (elecTxt.getText().equals("")) {
            errElec.setText("Please enter New electric index");
            errWater.setText(" ");
        } else if(!elecTxt.getText().matches("[0-9]+")) {
            errElec.setText("New electric contain numeric characters and not less than 0");
            errWater.setText(" ");
        } else if (Float.valueOf(elecTxt.getText()) < oldIndexElectric) {
            errElec.setText("New electric index not less than old index: " + oldIndexElectric);
            errWater.setText(" ");
        } else if (waterTxt.getText().equals("")) {
            errElec.setText(" ");
            errWater.setText("Please enter New water index");
        } else if(!waterTxt.getText().matches("[0-9]+")) {
            errElec.setText(" ");
            errWater.setText("New water contain numeric characters and not less than 0");
        } else if (Float.valueOf(waterTxt.getText()) < oldIndexWater) {
            errElec.setText(" ");
            errWater.setText("New water index not less than old index: " + oldIndexWater);
        }  else {
            errElec.setText(" ");
            errWater.setText(" ");
            
            int sttTmp = sttBill + 1;
            String idBill = "HOADON_0" + sttTmp +  "_" + idC;
            
            int month = monthTxt.getMonth() + 1;
            int day;
            if(sttBill == 0) {
                day = contractDAO.getDayContractBill(idC);
            } else {
                day = 10;
            }
            
            String tmp = yearTxt.getYear() + "-" + month + "-" + day;
            
            
            
            BillModel bill = new BillModel(idBill, idC, tmp, 0, false);
            
            
            
            double totalElectric = (Float.valueOf(elecTxt.getText()) - oldIndexElectric) * serDAO.getPrice("D");
            double totalWater = (Float.valueOf(waterTxt.getText()) - oldIndexWater) * serDAO.getPrice("N");
            
            if(billDAO.insertBill(bill)) {
                BillDetailModel electric = new BillDetailModel(bill.getIdBill(), "D", serDAO.getPrice("D"), oldIndexElectric, Float.valueOf(elecTxt.getText()), totalElectric, null);
                BillDetailModel water = new BillDetailModel(bill.getIdBill(), "N", serDAO.getPrice("N"), oldIndexElectric, Float.valueOf(waterTxt.getText()), totalWater, null);
                BillDetailModel internet = new BillDetailModel(bill.getIdBill(), "I", serDAO.getPrice("I"), 0, 1, serDAO.getPrice("I"), null);
                BillDetailModel trash = new BillDetailModel(bill.getIdBill(), "R", serDAO.getPrice("R"), 0, 1, serDAO.getPrice("R"), null);
                
                billDetailDAO.insertBillDetail(electric);
                billDetailDAO.insertBillDetail(water);
                billDetailDAO.insertBillDetail(internet);
                billDetailDAO.insertBillDetail(trash);
                
                double totalBill = totalElectric + totalWater + serDAO.getPrice("I") + serDAO.getPrice("R") + roomDAO.getPriceRoom(idR.getText());
                
                billDAO.updateTotalMoney(bill.getIdBill(), totalBill);
                
                JOptionPane.showMessageDialog(rootPane, "Successfully!!!");
                        this.dispose();
                    
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed!!!");
                this.dispose();
            }
        }
        
        
      
    }//GEN-LAST:event_addCusBTActionPerformed

    private void clcBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clcBTActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "You want to cancel?", "Message", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_clcBTActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CreateBillView dialog = new CreateBillView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCusBT;
    private javax.swing.JButton clcBT;
    private javax.swing.JTextField elecTxt;
    private javax.swing.JLabel errElec;
    private javax.swing.JLabel errWater;
    private javax.swing.JTextField idR;
    private javax.swing.JTextField internetTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JMonthChooser monthTxt;
    private javax.swing.JTextField oldElecText;
    private javax.swing.JTextField oldWaterTxt;
    private javax.swing.JTextField priceElecTxt;
    private javax.swing.JTextField priceInternet;
    private javax.swing.JTextField priceTrash;
    private javax.swing.JTextField priceWater;
    private javax.swing.JTextField trashTxt;
    private javax.swing.JTextField waterTxt;
    private com.toedter.calendar.JYearChooser yearTxt;
    // End of variables declaration//GEN-END:variables
}
