/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.AccountController;

/**
 *
 * @author nguye
 */
public class ForgotPasswdView extends javax.swing.JDialog {

    /**
     * Creates new form ForgotPasswdView
     */
    public ForgotPasswdView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Forgot password");
        
        hidePasswd.setVisible(true);
        showPasswd.setVisible(false);
        passwdTxt.setEchoChar('\u2022');
        
        
        hidePassConfirm.setVisible(true);
        showPassConfirm.setVisible(false);
        confirmPassTxt.setEchoChar('\u2022');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        errUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errPasswd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwdTxt = new javax.swing.JPasswordField();
        confirmPassTxt = new javax.swing.JPasswordField();
        errConfirmPasswd = new javax.swing.JLabel();
        changeBT = new javax.swing.JButton();
        showPasswd = new javax.swing.JLabel();
        hidePasswd = new javax.swing.JLabel();
        showPassConfirm = new javax.swing.JLabel();
        hidePassConfirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/forgot.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Username");

        errUserName.setForeground(new java.awt.Color(255, 0, 0));
        errUserName.setText(" ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("New password");

        errPasswd.setForeground(new java.awt.Color(255, 0, 0));
        errPasswd.setText(" ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Confirm password");

        errConfirmPasswd.setForeground(new java.awt.Color(255, 0, 0));
        errConfirmPasswd.setText(" ");

        changeBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changeBT.setText("CHANGE");
        changeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBTActionPerformed(evt);
            }
        });

        showPasswd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eye-16.png"))); // NOI18N
        showPasswd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPasswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswdMousePressed(evt);
            }
        });

        hidePasswd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-hide-16.png"))); // NOI18N
        hidePasswd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidePasswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePasswdMousePressed(evt);
            }
        });

        showPassConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eye-16.png"))); // NOI18N
        showPassConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPassConfirmMousePressed(evt);
            }
        });

        hidePassConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-hide-16.png"))); // NOI18N
        hidePassConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidePassConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassConfirmMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(userNameTxt)
                    .addComponent(passwdTxt)
                    .addComponent(confirmPassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(errPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errConfirmPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPasswd)
                    .addComponent(hidePasswd)
                    .addComponent(showPassConfirm)
                    .addComponent(hidePassConfirm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errUserName)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hidePasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errPasswd)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hidePassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errConfirmPasswd)
                .addGap(35, 35, 35)
                .addComponent(changeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBTActionPerformed
        // TODO add your handling code here:
        String pass = String.valueOf(passwdTxt.getPassword());
        String confirm = String.valueOf(confirmPassTxt.getPassword());
        
       if (new AccountController().getAccount(userNameTxt.getText()) == null) {
           errUserName.setText("Account does not exists");
           errPasswd.setText(" ");
           errConfirmPasswd.setText(" ");
       } else if (pass.equals("")) {
           errUserName.setText(" ");
           errPasswd.setText("Please enter password");
           errConfirmPasswd.setText(" ");
       } else if (!pass.matches("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,}$")) {
           errUserName.setText(" ");
           errPasswd.setText("Minimum 6 characters, at least 1 letter, 1 number");
           errConfirmPasswd.setText(" ");
       } else if (confirm.equals("")) {
           errUserName.setText(" ");
           errPasswd.setText(" ");
           errConfirmPasswd.setText("Please enter confirm password");
       } else if (!confirm.equals(pass)) {
           errUserName.setText(" ");
           errPasswd.setText(" ");
           errConfirmPasswd.setText("Does not match");
       } else {
           errUserName.setText(" ");
           errPasswd.setText(" ");
           errConfirmPasswd.setText(" ");
       }
    }//GEN-LAST:event_changeBTActionPerformed

    private void showPasswdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswdMousePressed
        hidePasswd.setVisible(true);
        showPasswd.setVisible(false);
        passwdTxt.setEchoChar('\u2022');
    }//GEN-LAST:event_showPasswdMousePressed

    private void hidePasswdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePasswdMousePressed
        hidePasswd.setVisible(false);
        showPasswd.setVisible(true);
        passwdTxt.setEchoChar((char)0);
    }//GEN-LAST:event_hidePasswdMousePressed

    private void showPassConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassConfirmMousePressed
        // TODO add your handling code here:
        hidePassConfirm.setVisible(true);
        showPassConfirm.setVisible(false);
        confirmPassTxt.setEchoChar('\u2022');
    }//GEN-LAST:event_showPassConfirmMousePressed

    private void hidePassConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassConfirmMousePressed
        // TODO add your handling code here:
        hidePassConfirm.setVisible(false);
        showPassConfirm.setVisible(true);
        confirmPassTxt.setEchoChar((char)0);
    }//GEN-LAST:event_hidePassConfirmMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswdView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ForgotPasswdView dialog = new ForgotPasswdView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeBT;
    private javax.swing.JPasswordField confirmPassTxt;
    private javax.swing.JLabel errConfirmPasswd;
    private javax.swing.JLabel errPasswd;
    private javax.swing.JLabel errUserName;
    private javax.swing.JLabel hidePassConfirm;
    private javax.swing.JLabel hidePasswd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwdTxt;
    private javax.swing.JLabel showPassConfirm;
    private javax.swing.JLabel showPasswd;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
